language: generic
addons:
  ssh_known_hosts:
  - "$DEPLOY_SERVER_HOST"
  - "$DEPLOY_SERVER_HOST_IP"
before_install:
- openssl aes-256-cbc -K $encrypted_64c8c3f595c3_key -iv $encrypted_64c8c3f595c3_iv
  -in deploy/deploy_ipaddress.enc -out /tmp/deploy_ipaddress -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_ipaddress
- ssh-add /tmp/deploy_ipaddress
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy/deploy.sh
  on:
    branch: master
notifications:
  slack:
    secure: AxW/JCX/eM2KeGKzMYzCh8YPD+AGFjHgaM/dAhe3n5kJ5Zt5KnDV6YBUN39W9nMtnMsJeHh7W/mMnbOnn+SHyjHGGH6pyumghnVshUiXOBzuPRAZV3JiaTagkI/kUA5yBFNjEq2MISiJ2g7aEqICehwGo7n9IWn2LxQ/yrXWX0wCl546X4w80PvM+E45z03AfiXOz7ZQIqOCIbbLTQjobo5uqWGVJYWh9fZ3WDqVtOWyHHhpEypPX7EgXpU06Sk2llieQLfNyzI0foZy+vwWWYGn+IuaFtEWMiBFkkxLbjNLN38nzUYXKnf77SENQxMY+dZSFhx31lAHFYOQ8Pi3qjZeJoJMyteVg1n8ui3il0GYYNQKkGZI7o6cKgwaQXL+ilGkeB+rTEK8WaINVFFBZZ9uMDBmbnOqj9Nf3d41OUgV47EKmLU84wh9skNbYxqyx4rRVbFRUZfbjg+vfkts2GcsBibYlKNiwnwQDeO0oQajn+hMgSXKO/+F3ZhOX5yZ6BKXsMRJrlCklLOs0ZIAUwn8pkC0Z6oY2GNqWIBa0iDYxeIBrlr5+CQSvy6PolKdslQtyuZVL1e4L5ATdeCinfGdxR9YTmLwJajvW6NXEH5dus876EvgqM9OojXFHF/277tIDpZd3QqSRwafvuxdIpfTyMktD4Wv8/IXa3V2peU=
