language: generic
addons:
  ssh_known_hosts:
  - "$DEPLOY_SERVER_HOST"
  - "$DEPLOY_SERVER_HOST_IP"
before_install:
- openssl aes-256-cbc -K $encrypted_64c8c3f595c3_key -iv $encrypted_64c8c3f595c3_iv
  -in deploy/deploy_ipaddress.enc -out /tmp/deploy_ipaddress -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_ipaddress
- ssh-add /tmp/deploy_ipaddress
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy/deploy.sh
  on:
    branch: master
notifications:
  slack:
    secure: tPpzW5I9HBIQSkXRSJuHkmdKRGRoeQ9jUmzVmM+eZ8LN779xUc480lFr5gYQUbNm9RZ80Ecp7ilseuKrSfvwWZEQQORls8ZA6TW8JN2y95nnNAk4k+Y9a0lOzlBJeXc4QmDmGUxeLPnsW1Psa1bO3wYdzV/DCw0H4Ja2fvWl9QnvEtYaV82R8Jolctb/rEI+7OOqGi6YD6Naup64BaBkotjJZh/PHi7RlKxgxfvUwUjQnt35IqQQy7dXuTiHqermpuL5gr2L0pVIV2W/XxWLcmfDuCA7MtWWYEPav3Ev5a2VYUED7NkUc//AD5T73EUAyMOrUSNTTz+sUvTHsW1Lr9tx3JvcYsBwI86zMgqc7zG37Jmkm4NJB33l6Ro8Xnf/VqHcS39k3Fzaz5r9IlczY4S3P6Isl9TtC45ZkssnPbboWEFF5er43U4svh8OonHiXu/AN2790Wc/E0FwBHL5SGg8WOBXJs4w6/wCH9QmfhyxsXker6dwUQJFdXQwN9ZSu7xmBht3rBramT7/PLZNiQ9Pjtc9XJQxutV9xmtreE4hbgJlXhxMP/RqKo6FL35xWSVXNtnXufE0PaH6PshyTHOmbWAwF++ZWFyJi43EjGPPgdlhDkprRc21h0n57o0sQUEqykZOV3jOrTJEwnCnSTns4+azFB672ZEGdqXzIBY=
