language: generic
addons:
  ssh_known_hosts:
  - "$DEPLOY_SERVER_HOST"
  - "$DEPLOY_SERVER_HOST_IP"
before_install:
- openssl aes-256-cbc -K $encrypted_64c8c3f595c3_key -iv $encrypted_64c8c3f595c3_iv
  -in deploy/deploy_ipaddress.enc -out /tmp/deploy_ipaddress -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_ipaddress
- ssh-add /tmp/deploy_ipaddress
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy/deploy.sh
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: LTeqc2KLBuV6ibw+E6OrXpVWoH5602oaVtz4MAg0QtOEwMN+5LdGafAF4TjgM68xwGpbdaYe76aafCkGZgW3Ssam8hul0ShuT8XCid7MUoSrE1QDIZ/wv5Nf5mpBum9ue+owXVQXQg4GaGhnVYI7W8uqDluJKuexsg2gIBQI3U7Cr8US1gwdEvTf4D3LDrOm+YmuYClFF30OgEDBxIXiTIl3qnwmB2Z+QLLMc8Lf9WNi1YdExOC7IV8H/e2ibyLjL4G2dizRc/n9+PlFBntULt1qX0nKkJweMONn0VR7EvPuD7jT04bidDWb0nG2w/iTkzo1WURJObEIQHVfOJTlXd/h3WJHC2rzVOAkTLgz5sid2TvFwOWNUI95POPdGJtW58h/kBgH3uQR014Q5xMGtcdOZLoZLT4qTXHbBCUZ4QcP9D7T0sTOs/IDg/Dk22YLNPQ5xz59o82gpfIfns63laWqncL/HPy20G9HqCUnxs5EygQyMdU6MP5k2olTur8SSZd+Yihk+I789d0yf8l/dEQpb6fw3G5sozsTRQwFB/ALJ2F/j2Vg2LtbV+7Qgi1VzPP/oz9zAf5vgEnSF6R3JDBOJHdd5YYel/hNVepYTQAt6cVGboMopLvBc4K6nwVppjsy6+uwHsda15yLSzkhfu1ER6I/iKzlTpajIH7BRT8=
